In [3]:
from random import randint
lista = []
for i in range(10):
    lista.append(randint(0,50))
lista

[16, 27, 31, 43, 18, 43, 26, 20, 38, 42]

In [5]:
for i in range(10):
    print(i+1)

1
2
3
4
5
6
7
8
9
10


In [4]:
import numpy as np
a = np.random.randint(0,100,10)
b = np.random.randint(0,100,10)
print('a', a)
print('b', b)

a [12 32 60 13 44 29 14 80  1 18]
b [42 87 29 39 17 12 14 18 97 73]


In [6]:
prod_escalar = np.dot(a,b)
prod_escalar

9678

In [7]:
m_filas = 5
n_cols = 3
mat_a = np.random.rand(m_filas,n_cols)
mat_a

array([[0.15002117, 0.27830657, 0.893816  ],
       [0.49805018, 0.9283007 , 0.03917655],
       [0.29482615, 0.06133588, 0.18324493],
       [0.99937155, 0.06876924, 0.04287303],
       [0.07386939, 0.42594399, 0.39152416]])

In [8]:
mat_b = np.random.rand(m_filas,n_cols)
mat_b

array([[0.47183603, 0.32636835, 0.94170502],
       [0.84305111, 0.91845172, 0.32127234],
       [0.10818422, 0.64807768, 0.58584482],
       [0.45565586, 0.45737693, 0.25601534],
       [0.51111521, 0.50299077, 0.62971613]])

In [11]:
suma_mat = mat_a+mat_b
suma_mat

array([[0.6218572 , 0.60467492, 1.83552101],
       [1.34110129, 1.84675242, 0.36044889],
       [0.40301037, 0.70941357, 0.76908974],
       [1.45502741, 0.52614617, 0.29888838],
       [0.5849846 , 0.92893476, 1.02124029]])

In [14]:
prod = mat_a*mat_b
prod

array([[0.0707854 , 0.09083046, 0.84171101],
       [0.41988176, 0.85259938, 0.01258634],
       [0.03189554, 0.03975042, 0.10735309],
       [0.45536951, 0.03145347, 0.01097615],
       [0.03775577, 0.2142459 , 0.24654908]])

In [15]:
prod_1 = np.multiply(mat_a, mat_b)
prod_1

array([[0.0707854 , 0.09083046, 0.84171101],
       [0.41988176, 0.85259938, 0.01258634],
       [0.03189554, 0.03975042, 0.10735309],
       [0.45536951, 0.03145347, 0.01097615],
       [0.03775577, 0.2142459 , 0.24654908]])

In [17]:
prod_mat = np.dot(mat_a, np.transpose(mat_b))
prod_mat

array([[1.00332686, 0.66924503, 0.72023167, 0.42447964, 0.77951409],
       [0.57485873, 1.28506747, 0.67844351, 0.6615526 , 0.74615781],
       [0.33169036, 0.36375909, 0.17899904, 0.2093064 , 0.2969338 ],
       [0.53435736, 0.91945645, 0.17780099, 0.49779913, 0.57238213],
       [0.54256914, 0.57927055, 0.5134087 , 0.32871217, 0.49855074]])